package com.order.service.domain;

public enum SodaOrderEventEnum {
    VALIDATE_ORDER, VALIDATION_PASSED, VALIDATION_FAILED, ALLOCATION_SUCCESS, ALLOCATION_NO_INVENTORY,
    ALLOCATION_FAILED, SODA_ORDER_PICKED_UP
}
